### ISSUE TITLE
discuss：这是一个讨论不是一个问题。

### ISSUE THREAD

**Issue by chengazhen** [IcarusRyy/NewJob#2]
作者您好，我在文档看到你为非程序员用户准备了usebuild 分支提供他们使用，我想你可以在release功能里面做这个操作。这样也不用多开一个分支。
1. 直接在release里面上传构建的代码就好
2. 使用github action 进行打包构建自动上传到release方面。这样更加方便。（此处我没有实践过，弄过类似的功能，我想这样大概率也是可行的）

**Comment by IcarusRyy** [comment]
好主意，后面可以改成这样的。我看他们评论，不知道github是什么东西，然后我就考虑的怎么傻瓜式教学怎么来吧 最简单理解就好 😄

**Comment by puxiao** [comment]
非程序员(无梯子)可能连 github 都打不开，不如来一个 百度网盘 或 阿里云盘 更直接。
不过我有一个疑问：获取到的工作修改时间 lastModifyTime 前台都不展示但为什么都能获取到？
还有，假设 BOSS 针对招聘岗位 也像简历那样推出一个 “每天自动刷新岗位” 的收费功能，你又该如何判断？

**Comment by chengazhen** [comment]
> 非程序员(无梯子)可能连 github 都打不开，不如来一个 百度网盘 或 阿里云盘 更直接。 不过我有一个疑问：获取到的工作修改时间 lastModifyTime 前台都不展示但为什么都能获取到？ 还有，假设 BOSS 针对招聘岗位 也像简历那样推出一个 “每天自动刷新岗位” 的收费功能，你又该如何判断？

在app端是有展示人事是否活跃的, 这个字段大概率是用来判断发布岗位的人是否活跃的一个字段。当然如果boss修改了这个字段, 感觉对于这个插件来说是一个灭顶之灾

**Comment by IcarusRyy** [comment]
> 非程序员(无梯子)可能连 github 都打不开，不如来一个 百度网盘 或 阿里云盘 更直接。 不过我有一个疑问：获取到的工作修改时间 lastModifyTime 前台都不展示但为什么都能获取到？ 还有，假设 BOSS 针对招聘岗位 也像简历那样推出一个 “每天自动刷新岗位” 的收费功能，你又该如何判断？

能判断就判断 不能的话 那就没办法了 大家都没得用了  首先 这个解决的痛点就是方便大家在浏览职位列表的时候 能精准定位目标岗位  如果改字段  依然对外暴露的话 那插件也能改  如果去除这个数据 那就GG 大家都没得玩了 hahaha

**Comment by IcarusRyy** [comment]
> > 非程序员(无梯子)可能连 github 都打不开，不如来一个 百度网盘 或 阿里云盘 更直接。 不过我有一个疑问：获取到的工作修改时间 lastModifyTime 前台都不展示但为什么都能获取到？ 还有，假设 BOSS 针对招聘岗位 也像简历那样推出一个 “每天自动刷新岗位” 的收费功能，你又该如何判断？
> 
> 在app端是有展示人事是否活跃的, 这个字段大概率是用来判断发布岗位的人是否活跃的一个字段。当然如果boss修改了这个字段, 感觉对于这个插件来说是一个灭顶之灾



> > 非程序员(无梯子)可能连 github 都打不开，不如来一个 百度网盘 或 阿里云盘 更直接。 不过我有一个疑问：获取到的工作修改时间 lastModifyTime 前台都不展示但为什么都能获取到？ 还有，假设 BOSS 针对招聘岗位 也像简历那样推出一个 “每天自动刷新岗位” 的收费功能，你又该如何判断？
> 
> 在app端是有展示人事是否活跃的, 这个字段大概率是用来判断发布岗位的人是否活跃的一个字段。当然如果boss修改了这个字段, 感觉对于这个插件来说是一个灭顶之灾

只能跟着一起改 hahha

**Comment by IcarusRyy** [comment]
> > 非程序员(无梯子)可能连 github 都打不开，不如来一个 百度网盘 或 阿里云盘 更直接。 不过我有一个疑问：获取到的工作修改时间 lastModifyTime 前台都不展示但为什么都能获取到？ 还有，假设 BOSS 针对招聘岗位 也像简历那样推出一个 “每天自动刷新岗位” 的收费功能，你又该如何判断？
> 
> 在app端是有展示人事是否活跃的, 这个字段大概率是用来判断发布岗位的人是否活跃的一个字段。当然如果boss修改了这个字段, 感觉对于这个插件来说是一个灭顶之灾

boss 凉了   字段没了 hahahhaha
